export const ERROR_CODES = {
  VALIDATION_ERROR: "E001",
  NOT_FOUND: "E002",
  DATABASE_FAILURE: "E003",
  UNAUTHORIZED: "E004",
  FORBIDDEN: "E005",
  INTERNAL_ERROR: "E500",
};

export default ERROR_CODES;
